// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUv9NxoSSlmbrs1O7hawBiEx8wiAMG7l4',
    appId: '1:116960679877:web:f05b0f7c277629c47c1dac',
    messagingSenderId: '116960679877',
    projectId: 'omedia-30ec6',
    authDomain: 'omedia-30ec6.firebaseapp.com',
    storageBucket: 'omedia-30ec6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpQU2iUsZT_ACQKWLPPrrhGO8CYNrlQI',
    appId: '1:116960679877:android:513798f80a2661227c1dac',
    messagingSenderId: '116960679877',
    projectId: 'omedia-30ec6',
    storageBucket: 'omedia-30ec6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDuMJZEu8Cs-zN-1JuRkxnnTei48BSZ3k',
    appId: '1:116960679877:ios:fcc6df7e0913f5097c1dac',
    messagingSenderId: '116960679877',
    projectId: 'omedia-30ec6',
    storageBucket: 'omedia-30ec6.appspot.com',
    iosBundleId: 'com.example.oRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDuMJZEu8Cs-zN-1JuRkxnnTei48BSZ3k',
    appId: '1:116960679877:ios:2fa0e2cd9aad9d117c1dac',
    messagingSenderId: '116960679877',
    projectId: 'omedia-30ec6',
    storageBucket: 'omedia-30ec6.appspot.com',
    iosBundleId: 'com.example.oRider.RunnerTests',
  );
}
